# Generated by Django 5.0.7 on 2024-08-09 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inmueble', models.TextField()),
                ('descripcion', models.CharField(max_length=200)),
                ('m2_construidos', models.FloatField()),
                ('numero_banos', models.IntegerField(default=0)),
                ('numero_hab', models.ImageField(default=0, upload_to='')),
                ('direccion', models.CharField(max_length=200)),
                ('id_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.comuna')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.region')),
                ('id_tipo_inmueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.tipo_inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
                ('correo', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipo_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.tipo_user')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
