# Generated by Django 5.0.7 on 2024-08-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='m2_construidos',
            field=models.FloatField(default=0),
        ),
    ]
