# Generated by Django 5.0.7 on 2024-08-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_alter_inmuebles_m2_construidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='numero_est',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
