# Generated by Django 5.0.7 on 2024-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0003_inmuebles_numero_est'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='m2_construidos',
            new_name='m2_construido',
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='m2_terreno',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='numero_est',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='numero_hab',
            field=models.IntegerField(default=0),
        ),
    ]
